# Generated by Django 4.1.1 on 2022-09-25 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Introduce el nombre del director", max_length=70
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Introduce el apellido del director", max_length=70
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Introduce el genero", max_length=60),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Introduce el nombre de la pelicula", max_length=50
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Sinopsis de la pelicula", max_length=100
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.director",
                    ),
                ),
                ("gender", models.ManyToManyField(to="catalog.gender")),
            ],
        ),
    ]
