# Generated by Django 4.1.1 on 2022-09-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="premier",
            field=models.DateField(null=True),
        ),
    ]
